environment: development

apphost: k8s

label:
  name: aspnet3core

container:
  name: aspnet3
  pullPolicy: IfNotPresent
  image: nirajdock/weatherweb
  tag: latest
  port: 80
replicas: 3

service:
  port: 34343
  type: ClusterIP
