version: '3.4'

services:
  webapp:
    image: mcr.microsoft.com/dotnet/core/samples:aspnetapp
    ports:
      - 80
      - 443
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=/run/secrets/viz-server-key
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/run/secrets/viz-server-cert
    secrets:
      - viz-server-cert
      - viz-server-key
secrets:
  viz-server-cert:
    external: true
  viz-server-key:
    external: true